### ISSUE TITLE
Investigate parsing

### ISSUE THREAD

**Issue by BenFradet** [snowplow-referer-parser/jvm-referer-parser#13]
- snowplow-referer-parser/referer-parser#188
- snowplow-referer-parser/referer-parser#36

**Comment by three** [comment]
Following page_referrer string from referer-parser#188 goes to a yandex search whose query is a redirect page url, and that's extracted. The query from referer-parser#36 is extracted as "g star". I'm not sure how a search for the redirect page became the referer, but I think referer-parser it's behaving as expected.

**Comment by BenFradet** [comment]
Thanks, closing
